### ISSUE TITLE
Support for Private packages 

### ISSUE THREAD

**Issue by snoweel** [Nohmapp/npm-introspect#8]
Does npm-introspect support private packages ? 
Was getting  below error as my project has some private packages as dependents .
I have removed the private package name from error message 

SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at buildVisualization (index.js:58)
    at Object.<anonymous> (d3.v4.min.js:2)
    at p.call (d3.v4.min.js:2)
    at XMLHttpRequest.e (d3.v4.min.js:2)

error response : 
{
  "name": "StatusCodeError",
  "statusCode": 404,
  "message": "404 - \"{\\\"code\\\":\\\"NOT_FOUND\\\",\\\"message\\\":\\\"The specified endpoint does not exist\\\"}\"",
  "error": "{\"code\":\"NOT_FOUND\",\"message\":\"The specified endpoint does not exist\"}",
  "options": {
    "uri": "https://api.npms.io/v2/package/<package-name>",
    "method": "GET",
    "simple": true,
    "resolveWithFullResponse": false,
    "transform2xxOnly": false
  },
  "response": {
    "statusCode": 404,
    "body": "{\"code\":\"NOT_FOUND\",\"message\":\"The specified endpoint does not exist\"}",
    "headers": {
      "date": "Fri, 18 Aug 2017 05:00:04 GMT",
      "content-type": "application/json; charset=utf-8",
      "content-length": "70"
    },
    "request": {
      "uri": {
        "protocol": "https:",
        "slashes": true,
        "auth": null,
        "host": "api.npms.io",
        "port": 443,
        "hostname": "api.npms.io",
        "hash": null,
        "search": null,
        "query": null,
        "pathname": "/v2/package/<package-name>",
        "path": "/v2/package/<package-name>",
        "href": "https://api.npms.io/v2/package/<package-name>"
      },
      "method": "GET",
      "headers": {}
    }
  }
}

Uncaught TypeError: Cannot read property 'sort' of undefined
    at buildVisualization (index.js:70)
    at Object.<anonymous> (d3.v4.min.js:2)
    at p.call (d3.v4.min.js:2)
    at XMLHttpRequest.e (d3.v4.min.js:2)

**Comment by Nohmapp** [comment]
Unfortunately it doesn't have support for private packages, the ratings are based on meta data around how people use and interact with the package, so private packages would return null on a lot of the statistics.

**Comment by snoweel** [comment]
Thanks for the update
