### ISSUE TITLE
Special characters like "@" or "/" in package names should be percent coded when querying

### ISSUE THREAD

**Issue by opirci** [Nohmapp/npm-introspect#9]
When examining an angular project dependencies, packages with name containing special characters like "@" or "/" should be percent coded when requesting from API. 

For instance "@angular/forms" package;
is requested as it is "https://api.npms.io/v2/package/@angular/common"
but should be as     "https://api.npms.io/v2/package/%40angular%2Fcommon"
to get the result.

Otherwise you get error message as attached
[ErrorMessage.txt](https://github.com/Nohmapp/npm-introspect/files/1236356/ErrorMessage.txt)

Special characters like "@" or "/" in package names should be percent coded when querying.

**Comment by Nohmapp** [comment]
Thanks- I'm making some other fixes now- thanks for letting me know.

**Comment by kikill95** [comment]
I have face this issue too with "@"

**Comment by z3dtech** [comment]
This has been addressed. See https://github.com/Nohmapp/npm-introspect/commit/328554321d1b531b2bd03e7b9184a8dc87457da1#diff-b7f78f3b0d4aafe5dfd7a8476ececa0bR130. I think it's time this issue was closed @Nohmapp.
